### ISSUE TITLE
@to watch

### ISSUE THREAD

**Issue by r-lyeh-archived** [r-lyeh/depot#1]
cool travis file
https://github.com/graphitemaster/neothyne/blob/master/.travis.yml

``` yaml
language: cpp

compiler:
  - gcc
  - clang

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make -j5 && sudo make install)

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; export EXTRAFLAGS=-D__extern_always_inline=inline; fi
  # Neothyne uses CC to prevent linking libstdc++
  - export CC=$CXX

script:
    - make

notifications:
    irc:
        channels:
          - "irc.freenode.org#gmqcc"
        template:
          - "[%{commit} : %{author}] %{message}"
          - "%{build_url}"
        skip_join: true
```
